### PR TITLE
Added some more translations

### PR DESCRIPTION
**Pull request by max-krichenbauer**
Added some more translations

### CODE REVIEW

**Comment by zaplitny** [comment]
Thanks a lot! Please mail at support@timetrack.io and I'll grant you premium subscription

**Comment by max-krichenbauer** [comment]
No need. ;-)
Sorry, I did just a bit for now because I have to finish something else.
Will continue working on it later.
Thanks so much for aTimeLogger!

**Comment by zaplitny** [comment]
This translation is for successor of aTimeLogger - http://timetrack.io. Are you using it already?

**Comment by max-krichenbauer** [comment]
Not yet, because I use android.
I'm looking forward to it.

**Comment by zaplitny** [comment]
There're strings that require some experience in new app. Ask me if you need explanation. P.S. Developing android app right now

**Pull request merged**
